name: CPython WASI Build

on:
  workflow_dispatch:
    inputs:
      cpython_branch:
        description: 'CPython branch to clone'
        required: true
        default: 'v3.13.2'
        type: string
      optimize_level:
        description: 'wasm-opt optimize level'
        required: true
        default: '4'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: CPython WASI Build in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/avril112113/build_cpython_wasi
          #cacheFrom: ghcr.io/avril112113/build_cpython_wasi
          #push: always
          env: |
            CPYTHON_BRANCH=${{ inputs.cpython_branch }}
            OPTIMIZE_LEVEL=${{ inputs.optimize_level }}
          runCmd: ./build-wasi.sh

      - uses: actions/upload-artifact@v4
        with:
          name: CPython-WASI-${{ inputs.cpython_branch }}
          path: ./out/
          if-no-files-found: error
      
      - uses: actions/upload-artifact@v4
        with:
          name: for_external_builds
          path: ./out/for_external_builds/
          if-no-files-found: error
      
      - uses: actions/upload-artifact@v4
        with:
          name: lib
          path: ./out/lib/
          if-no-files-found: error
      
      - run: echo "TMP_FILE_NAME=$(basename ./out/python*.wasm)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TMP_FILE_NAME }}
          path: ./out/${{ env.TMP_FILE_NAME }}
          if-no-files-found: error
      
      - run: echo "TMP_FILE_NAME=$(basename ./out/python*_async.wasm)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TMP_FILE_NAME }}
          path: ./out/${{ env.TMP_FILE_NAME }}
          if-no-files-found: error
